name: GetChannelMessages_release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.Slack.GetChannelMessages
      dotnet_version: 8.0.x
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
